### ISSUE TITLE
Add Firefox support

### ISSUE THREAD

**Issue by yannicka** [ExpressiveSuite/ExpressiveAnimator#68]
When I go to https://animator.expressive.app/ with Firefox, this is what the development console shows:

![image](https://user-images.githubusercontent.com/22885898/126036974-fa9fc2af-1552-4fe2-a734-4f2e33d6b538.png)

The web application does not launch and remains stuck on loading.

**Comment by msarca** [comment]
Firefox does not support compression/decompression streams. When FF implements them, that error will be gone. Until then, you can use Chrome or Edge; they are both free and based on the open-source Chromium project.

**Comment by yannicka** [comment]
Would it be possible to integrate a polyfill in the meantime?

**Comment by sorinsarca** [comment]
Since this issue was opened, I'll point out some of the features Firefox is missing.


- Streams

https://developer.mozilla.org/en-US/docs/Web/API/WritableStream
https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/pipeThrough
https://developer.mozilla.org/en-US/docs/Web/API/Compression_Streams_API

- File System API

https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API

- Local Font Access

https://www.chromestatus.com/feature/6234451761692672


Some of them may have a fallback, for example without File System API you will probably see the default Save dialog every time you save your project, and without Local Font Access you'll never be able to load fonts from your system.

But streams cannot be polyfilled.

**Comment by msarca** [comment]
> without File System API, you will probably see the default Save dialog every time you save your project

Technically, without File System API, you would be forced to **download** the project every time you want to save it.

Unfortunately, one of the biggest features that are still missing from Firefox is PWA support. Not only is that missing, but they announced that they would not be able to provide it. This makes me believe that they would not implement APIs like File System or Local Fonts very soon.

**Comment by booti386** [comment]
> But streams cannot be polyfilled.

https://www.npmjs.com/package/@stardazed/streams-polyfill

**Comment by msarca** [comment]
When Firefox catches up with Chromium-based browsers (Chrome, Edge, Opera, etc.), we will most certainly add support for it. However, until then, I'm afraid it is not possible.
